version: '3.5'
services:
#golang service
  app:
    container_name: myapp
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - myapp-postgres          # Uncomment this when using postgres.
      # - myapp-mysql           # Uncomment this when using mysql.
    networks:
      static_ip:
         ipv4_address: 198.168.1.1
         #- myapp               # Uncomment this when network is not static.


#postgres service
  myapp-postgres:
    image: postgres:latest
    container_name: mydb_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
     - database_postgres:/var/lib/postgresql/data
    networks:
      static_ip:
         ipv4_address: 198.168.1.2
    
#pgadmin service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - myapp-postgres
    ports:
      - "5050:80"
    networks:
      static_ip:
         ipv4_address: 198.168.1.3
    restart: unless-stopped

#nginx service
  nginx:
    container_name: nginx_container
    build: ./reverse-proxy
    networks:
      static_ip:
        ipv4_address: 198.168.1.4
    ports:
      - 80:80
      - 443:443


#mysql service
  # myapp-mysql:
  #   image: mysql:5.7
  #   container_name: mydb_mysql
  #   ports: 
  #     - 3306:3306
  #   environment: 
  #     - MYSQL_ROOT_HOST=${DB_HOST} 
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - database_mysql:/var/lib/mysql
  #   networks:
  #     - myapp
  
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin_container
  #   depends_on:
  #     - myapp-mysql
  #   environment:
  #     - PMA_HOST=mysql # Note the "mysql". Must be the name of the what you used as the mysql service.
  #     - PMA_USER=${DB_USER}
  #     - PMA_PORT=${DB_PORT}
  #     - PMA_PASSWORD=${DB_PASSWORD}
  #   ports:
  #     - 9090:80
  #   restart: always
  #   networks:
  #     - myapp


volumes:
  api:
  database_postgres:                  # Uncomment this when using postgres.
  # database_mysql:                   # Uncomment this when using mysql.

# Networks to be created to facilitate communication between containers
networks:
  static_ip:
    name: my_network
    ipam:
      driver: default
      config:
        - subnet: 198.168.0.0/20
